### ISSUE TITLE
202309：现在中国知网的官方软件"全球学术快报"已经可以免费，无限制，保留目录地把caj转换成pdf了

### ISSUE THREAD

**Issue by GHboy2018** [caj2pdf/caj2pdf#101]
发这个issue，只是想告诉那些还不知道的人：中国知网的官方软件[全球学术快报](http://m.cnki.net/mcnkidown/index.html)已经开放了caj转换pdf的功能，可以免费，无限制，保留目录地（对于学位论文）把caj转换成pdf。只要在"全球学术快报"登录自己的知网个人账号，在资料库中导入想要转换的caj文件，就可以方便地批量转换pdf了。批量转换的文件数如果有点多，软件可能会卡顿一下，稍等一下就好了。
![未命名图片](https://github.com/caj2pdf/caj2pdf/assets/40054495/faf159da-87ad-4ae9-b2ea-8ed648d2e73a)
caj2pdf当然也很不错，感谢开发者！不过现在既然官方软件已经开放了这个功能，我觉得大部分情况下，能用官方就用官方的吧。

我挑选了issue里提到的转换出错或失败的其中几个caj样本，测试了一下，用"全球学术快报"都可以正确完整地转换出pdf。

**Comment by fuxuelinwudi** [comment]
sima cnki
