### ISSUE TITLE
有没有一个方便的可以查看文件格式的软件？类似Apache PDFBox Debugger这种?

### ISSUE THREAD

**Issue by ruanxiao** [caj2pdf/caj2pdf#102]
问题如标题！

**Comment by HinTak** [comment]
See the README at https://github.com/caj2pdf/CAJSamples about the use of the magic file. This identifies the type variants of different CAJ files. If you are asking about identifying and debugging **content details** of a CAJ file, the answer is probably no.

You have to explain what Apache PDFBox Debugger does. No idea what it does, and also NOT INTERESTED. mutool (which caj2pdf uses) can disect pdf's. If that's not enough, from the same people as mutool, "gs -dPDFDEBUG ..." can disect pdf's too.
