### ISSUE TITLE
请问MacOS能否使用？目前使用报错

### ISSUE THREAD

**Issue by Roger1219** [caj2pdf/caj2pdf#103]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/caj2pdf/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 CAJ2PDF？
最新版
2) 你的使用场景是什么？比如convert还是其他。
convert出错，show正常
3) 你看到的不正常的现象是什么？（请描述具体现象，比如PDF打不开等）
找不到libjbigdec.so
OSError: dlopen(./libjbigdec.so, 0x0006):
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（Python版本、Python包版本以及mutools版本）。
miniconda 新建的环境 python 3.9  
7) 请使用××ZIP××格式压缩CAJ文件，附在此处。

8)  请附上出错时软件输出的错误信息。

错误信息:

```python
Traceback (most recent call last):
  File "/Users/roger/Documents/Code/caj2pdf/./caj2pdf", line 52, in <module>
    caj.convert(args.output)
  File "/Users/roger/Documents/Code/caj2pdf/cajparser.py", line 118, in convert
    self._convert_hn(dest)
  File "/Users/roger/Documents/Code/caj2pdf/cajparser.py", line 376, in _convert_hn
    from jbigdec import CImage
  File "/Users/roger/Documents/Code/caj2pdf/jbigdec.py", line 29, in <module>
    libjbigdec = cdll.LoadLibrary("./libjbigdec.so")
  File "/Users/roger/miniconda3/envs/caj2pdf/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/Users/roger/miniconda3/envs/caj2pdf/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./libjbigdec.so, 0x0006): tried: './libjbigdec.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS./libjbigdec.so' (no such file), '/Users/roger/miniconda3/envs/caj2pdf/lib/python3.9/lib-dynload/../.././libjbigdec.so' (no such file), '/Users/roger/miniconda3/envs/caj2pdf/bin/../lib/./libjbigdec.so' (no such file), '/usr/lib/./libjbigdec.so' (no such file, not in dyld cache), './libjbigdec.so' (no such file), '/Users/roger/Documents/Code/caj2pdf/libjbigdec.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/roger/Documents/Code/caj2pdf/libjbigdec.so' (no such file), '/Users/roger/Documents/Code/caj2pdf/libjbigdec.so' (no such file)
```

请预览一下你填的内容再提交。

**Comment by HinTak** [comment]
See  https://github.com/caj2pdf/caj2pdf?tab=readme-ov-file#how-far-weve-come on building libkbigdec.so

**Comment by HinTak** [comment]
Download the two *.so from https://github.com/caj2pdf/caj2pdf-extra-libs/releases/tag/BUILD-0.1, `chmod a+x ...` both, and copy them to any of the "no such file" locations  as shown in the error message.

They were built for Mac os x 12 (I think current). If you are on an older OS, you might have to do it yourself.
