### ISSUE TITLE
找到一个NH文件和所对应的官方PDF文件

### ISSUE THREAD

**Issue by ElonH** [caj2pdf/caj2pdf#29]
NH和PDF文件都是官方的文件。
看了一下两个hex值有一部分是相同的
pdf文件嵌入了字体
![image](https://user-images.githubusercontent.com/32666230/53698247-ef813080-3e14-11e9-876e-4a4efbd2d140.png)
每一页都多出了一个水印
![image](https://user-images.githubusercontent.com/32666230/53698259-13dd0d00-3e15-11e9-8f48-ac2a1cccf05c.png)
pdf制作工具是：
CNKI®ReaderEx(2.0.0 Build 3948)
pdf文件是没有outlines

[HN_and_PDF.zip](https://github.com/JeziL/caj2pdf/files/2923341/HN_and_PDF.zip)

**Comment by ElonH** [comment]
个人觉得HN和PDF都是从原文件制作出来的，但是有部分存在差异

**Comment by lelandyang** [comment]
硕士、博士毕业的时候，学校图书馆要求上传PDF版本的电子档案。因此源文件就是一个PDF文档。HN和PDF都是从原文件制作出来的这句话是对的。
如今魔改PDF生成的CAJ文件已经可以对付，但是NH无法搞定。
你上面说的PDF文件其实生成路径是： 学生上传的PDF --> NH --> 转换出的PDF。
根据PDF的meta属性可以看出上面是ReadEx，其实也就是libReaderEx.dll里面封装的转换函数（我猜测这个函数在CNKI Reader里面也存在，但是这个动态链接库的导出表被抹掉了，是用的索引调用的，给逆向带来了一定的难度。）

**Comment by HinTak** [comment]
The Linux viewer (released earlier this year) has a libReaderEx_x64.so - it is slightly more helpful than the old android one, for one reason: pointers are 64-bit and nm distinguishs between pointers vs 32-bit int, and therefore also which routines are static methods, and function prototypes are clearer.

**Comment by HinTak** [comment]
`nm -C -D` gives quite good prototype information. One can probably write a new header file and link against `libreaderex_x64.so` to study it.

**Comment by lelandyang** [comment]
Yes, I think you right. The reason for the recommendation was that Android version was available earlier than Linux version, and the interface was clear considering its Java code, which was not encrypted.
I mainly employed static analyses for analyzing the library, not dynamic ones cause dlls are not so easy to dbg.
But perhaps we can create a repo to contain analysis tools, reversed headers and caj samples as these files are not so easily accessible outside of university campus.

**Comment by HinTak** [comment]
Yes I understand the android one is a lot older. I would be interested in reading the Linux version decompiled - anybody know the person who did the android one and/or can do similar things?

Anyway, I am hoping to update the wiki with a "reverse-engineering" page.

**Comment by lelandyang** [comment]
Android decompiled c-style source for the library can be found on github.
Perhaps you might be disappointed cause according to my analyses, the libreaderex is available on different platforms which indicates that it's just one piece of code cross-platform compiled with minor modification for platform specific adjustment.
Almost every piece of code comes with similar path, something like:
C:\Cofan\MyWork\ on windows
and /library/Cofan/MyWork on macOS, 
where CoFan is one of the emploees with the surname 范 from the software developer whose information can be found on Linkedin.

**Comment by HinTak** [comment]
This now converts well - here is the result:
[阈上和阈下奖励对无意识剌激诱发的反应抑制的影响_刁留亭.pdf](https://github.com/caj2pdf/caj2pdf/files/5788394/_.pdf)

remaining issues with HN files are tracked in #57 .
