### ISSUE TITLE
几个不能转换的例子文件

### ISSUE THREAD

**Issue by maris205** [caj2pdf/caj2pdf#33]
[caj_error.zip](https://github.com/JeziL/caj2pdf/files/3215965/caj_error.zip)
其中test3.caj, 和test2.caj 文本打开看了下，是pdf格式的，改扩展名成pdf就能用了
可以专门识别下
test1.caj显示Unknown file type.

**Comment by JeziL** [comment]
test1 类型未知

**Comment by lelandyang** [comment]
@JeziL 这个类型是北大二扫型，专用于杂志。KDH也一样。caj2pdf可以先考虑支持NH型

**Comment by HinTak** [comment]
test1 has a 0xC8 header and is close enough to HN file type, so it is now processed as such. Here is the converted result:

[test1.pdf](https://github.com/caj2pdf/caj2pdf/files/5788452/test1.pdf)

Remaining issues are tracked in #57 .
