### ISSUE TITLE
发现了一个转换不了的文件

### ISSUE THREAD

**Issue by 1208zhangyang** [caj2pdf/caj2pdf#34]
[G公司医药移动电子商务平台项目可行性研究_邓晓聪.zip](https://github.com/JeziL/caj2pdf/files/3216835/G._.zip)

**Comment by JeziL** [comment]
KDH 样本

**Comment by HinTak** [comment]
This seems to work well now, sample files put under the CAJSamples repo for future testing.

**Comment by HinTak** [comment]
Here is the converted result from current dev code:
[G公司医药移动电子商务平台项目可行性研究_邓晓聪.pdf](https://github.com/caj2pdf/caj2pdf/files/5788473/G._.pdf)
