### ISSUE TITLE
C rewrite

### ISSUE THREAD

**Issue by ghost** [caj2pdf/caj2pdf#45]
I produced another version of the converter written in C. It has no external dependences. You can find my project here [austerios/melon](https://github.com/austerios/melon).

I registered an account just for this. NH needs more work.

**Comment by HinTak** [comment]
The github repo no longer works. The current place is https://git.noema.org/melon/ . It seems that he does something differently; the code is quite buggy... Anyway, HN file works well here and remaining issues is tracked at #57 .

I don't think we need to keep this open - we'd like to fix #49 , probably by studying what the c rewrite does differently; but we are quite a lot ahead with HN files.
