### ISSUE TITLE
书签目标错误

### ISSUE THREAD

**Issue by SainoNamkho** [caj2pdf/caj2pdf#47]
在 SumatraPDF 3.2中，书签被定位到页面底部，3.1.2 正常。（虽然可能是SumatraPDF 的bug，不过那边积压的bug太多，这边修改相对容易）。
### 复现方法
caj文件:[依据书法笔力对运笔基本问题的再认识_刘玉栋.zip](https://github.com/JeziL/caj2pdf/files/4490478/_.zip)

由于无法convert，我下载了无书签的pdf版本：[依据书法笔力对运笔基本问题的再认识_刘玉栋.pdf](https://github.com/JeziL/caj2pdf/files/4490477/_.pdf)

` caj2pdf outlines` 之后：[output.pdf](https://github.com/JeziL/caj2pdf/files/4490500/output.pdf)
SumatraPDF “视图”->“连续显示页面”，点击指向第4页的书签：
![image](https://user-images.githubusercontent.com/23036788/79522961-a2e7cb80-808f-11ea-8456-a0eaf3a4ce60.png)
窗口顶端定位于第4页底部，主体为第5页：
![image](https://user-images.githubusercontent.com/23036788/79523286-5d77ce00-8090-11ea-9c35-80f8ad77a38c.png)

### 建议修改
[utils.py](/JeziL/caj2pdf/blob/master/utils.py#L150) 改为
```python
def make_dest(pdfw, pg):
    d = PDF.ArrayObject()
    d.append(pdfw.getPage(pg).indirectRef)
    d.append(PDF.NameObject("/Fit"))
    return d
```

**Comment by HinTak** [comment]
The bookmark navigation seems to work identically, running xpdf against the caj2pdf version and libreaderex version. With current code.
