### ISSUE TITLE
file type unsupported sample

### ISSUE THREAD

**Issue by Xpectuer** [caj2pdf/caj2pdf#50]
提供一个样本
[sample.zip](https://github.com/JeziL/caj2pdf/files/4906378/sample.zip)

**Comment by lelandyang** [comment]
@JeziL @Xpectuer 
+ 技术不行，转换之后出现了空白页。
+ 这个样本和我之前提到的 https://github.com/JeziL/caj2pdf/issues/43 是同一类型，按照Wiki中的格式分析，转换出来没有插图。
+ 附件（转换后的该Sample）：
[Conv.zip](https://github.com/JeziL/caj2pdf/files/5445413/Conv.zip)

**Comment by HinTak** [comment]
This now converts well enough. Here is the result:
[基于群体协同的交通态势感知服务系统的研究与实现_高尚.pdf](https://github.com/caj2pdf/caj2pdf/files/5788785/_.pdf)

Remaining issues are tracked in #57 .
