### ISSUE TITLE
Pull "Analysing libreaderex" into wiki

### ISSUE THREAD

**Issue by HinTak** [caj2pdf/caj2pdf#54]
There does not seems to be a way for me to issue a pull to update the wiki. So I am filing this issue.

the wiki is a hidden git repo with `.wiki` added to the end. You can merge mine (found online at https://github.com/HinTak/caj2pdf/wiki ) by doing this to merge my changes:

```
git clone git@github.com:caj2pdf/caj2pdf.wiki.git
cd caj2pdf.wiki
git pull https://github.com/HinTak/caj2pdf.wiki.git
git push
```

There are only three changes - a new "Analysing libreaderex" doc, a reference to it from the main page, and also adjusting
all wiki URLs to be relative (so that it does not jump between mine and yours).

**Comment by JeziL** [comment]
I think this libreaderex thing is really worth digging in, so I made caj2pdf an organizaiton repo. After accepting the membership invitation,  you (and several other contributors) will be able to edit the wiki.

Really amazing work. Sadly I don't have that much time for this project these days but happy to see that people are still pushing it forward.
