### ISSUE TITLE
你好，libjbig2codec.so和libjbigdec.so在哪里？

### ISSUE THREAD

**Issue by ttxiaoxitt** [caj2pdf/caj2pdf#67]
你好，libjbig2codec.so和libjbigdec.so在哪里？

**Comment by HinTak** [comment]
Source code in the lib directory, https://github.com/caj2pdf/caj2pdf/tree/master/lib, build instruction near the top of files. Windows binaries in lib/bin.

**Comment by ttxiaoxitt** [comment]
hi, I can't get libjbig2codec.so with this error.

cc -Wall `pkg-config --cflags poppler` -fPIC -shared -o libjbig2codec.so decode_jbig2data.cc `pkg-config --libs poppler`
Package poppler was not found in the pkg-config search path.
Perhaps you should add the directory containing `poppler.pc'
to the PKG_CONFIG_PATH environment variable
Package 'poppler', required by 'virtual:world', not found
Package poppler was not found in the pkg-config search path.
Perhaps you should add the directory containing `poppler.pc'
to the PKG_CONFIG_PATH environment variable
Package 'poppler', required by 'virtual:world', not found
decode_jbig2data.cc:13:10: fatal error: JBIG2Stream.h: No such file or directory
   13 | #include "JBIG2Stream.h"

cc -Wall `pkg-config --cflags jbig2dec` -fPIC -shared -o libjbig2codec.so decode_jbig2data_x.cc `pkg-config --libs jbig2dec`
Package jbig2dec was not found in the pkg-config search path.
Perhaps you should add the directory containing `jbig2dec.pc'
to the PKG_CONFIG_PATH environment variable
Package 'jbig2dec', required by 'virtual:world', not found
Package jbig2dec was not found in the pkg-config search path.
Perhaps you should add the directory containing `jbig2dec.pc'
to the PKG_CONFIG_PATH environment variable
Package 'jbig2dec', required by 'virtual:world', not found
decode_jbig2data_x.cc:27:10: fatal error: jbig2.h: No such file or directory
   27 | #include "jbig2.h"

**Comment by ttxiaoxitt** [comment]
do you know where is JBIG2Stream.h or jbig2.h?

**Comment by HinTak** [comment]
It is in the front page - you need either of libpoppler开发包，或libjbig2dec开发包 .

**Comment by ttxiaoxitt** [comment]
你好，我下载了libjbig2dec开发包，并且编译出来了libjbig2codec.so，但是编译出来的有问题，感觉是不是libjbig2dec开发包的版本和您工程使用的版本不一致？

**Comment by ttxiaoxitt** [comment]
cc -Wall `pkg-config --cflags jbig2dec` -fPIC -shared -o libjbig2codec.so decode_jbig2data_x.cc `pkg-config --libs jbig2dec`
Package jbig2dec was not found in the pkg-config search path.
Perhaps you should add the directory containing `jbig2dec.pc'
to the PKG_CONFIG_PATH environment variable
Package 'jbig2dec', required by 'virtual:world', not found
Package jbig2dec was not found in the pkg-config search path.
Perhaps you should add the directory containing `jbig2dec.pc'
to the PKG_CONFIG_PATH environment variable
Package 'jbig2dec', required by 'virtual:world', not found

**Comment by ttxiaoxitt** [comment]
发生异常: OSError
./libjbig2codec.so: undefined symbol: jbig2_page_out
  File "/mnt/c/mcPro/project/caj2pdf/jbig2dec.py", line 28, in <module>
    libjbig2codec = cdll.LoadLibrary("./libjbig2codec.so")

**Comment by HinTak** [comment]
Please try libpoppler instead then. libjbig2dec has not changed for over a decade, but it can be built to hide all internal symbols (as is seen in your error message).

**Comment by ttxiaoxitt** [comment]
Hello，Which version of libpoppler do you use? I downloaded several versions of libpoppler, and the header file was missing when compiling.

**Comment by HinTak** [comment]
I don't think it matters - the part of libpoppler used has been there for decades and unchanged too

**Comment by aaiccee** [comment]
cc -Wall `pkg-config --cflags poppler` -fPIC -shared -o libjbig2codec.so decode_jbig2data.cc `pkg-config --libs poppler`
执行发生错误，
decode_jbig2data.cc: In function ‘int decode_jbig2data(char*, int, char*, int, int, int, int)’:
decode_jbig2data.cc:29:67: error: no matching function for call to ‘Object::Object(ObjType)’
   MemStream *v10 = new MemStream(inbuf, 0, bufsize, Object(objNull));
                                                                   ^
decode_jbig2data.cc:29:67: note: candidates are:
In file included from /usr/include/poppler/JBIG2Stream.h:32:0,
                 from decode_jbig2data.cc:13:
/usr/include/poppler/Object.h:121:3: note: Object::Object()
   Object():
   ^
/usr/include/poppler/Object.h:121:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/poppler/Object.h:115:7: note: Object::Object(const Object&)
 class Object {
       ^
/usr/include/poppler/Object.h:115:7: note:   no known conversion for argument 1 from ‘ObjType’ to ‘const Object&’
decode_jbig2data.cc:30:52: error: no matching function for call to ‘Object::Object(ObjType)’
   Stream *v11 = new JBIG2Stream(v10, Object(objNull), &globals);
                                                    ^
decode_jbig2data.cc:30:52: note: candidates are:
In file included from /usr/include/poppler/JBIG2Stream.h:32:0,
                 from decode_jbig2data.cc:13:
/usr/include/poppler/Object.h:121:3: note: Object::Object()
   Object():
   ^
/usr/include/poppler/Object.h:121:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/poppler/Object.h:115:7: note: Object::Object(const Object&)
 class Object {
       ^
/usr/include/poppler/Object.h:115:7: note:   no known conversion for argument 1 from ‘ObjType’ to ‘const Object&’
修改：
decode_jbig2data.cc
/*
  Copyright 2021 (c) Hin-Tak Leung <htl10@users.sourceforge.net>
  See The FreeType Project LICENSE for license terms.

  This is a small wrapper around libpoppler to provide a python
  interface to decode JBIG2 stream.

  To build:

      cc -Wall `pkg-config --cflags poppler` -fPIC -shared -o libjbig2codec.so decode_jbig2data_new.cc `pkg-config --libs poppler`
*/

#include "JBIG2Stream.h"

int decode_jbig2data(char*, int, char*, int, int, int, int);

extern "C" {
int decode_jbig2data_c(char* inbuf, int bufsize, char* outptr, int width, int height, int width_in_padded_4bytes, int width_in_padded_bytes)
{
  return decode_jbig2data(inbuf, bufsize, outptr, width, height, width_in_padded_4bytes, width_in_padded_bytes);
}
}

int decode_jbig2data(char* inbuf, int bufsize, char* outptr, int width, int height, int width_in_padded_4bytes, int width_in_padded_bytes)
{
  int v12;

  Object objNull;
  Object globals;
  MemStream *v10 = new MemStream(inbuf, 0, bufsize, &objNull); // Pass the address of objNull
  JBIG2Stream *v11 = new JBIG2Stream(v10, &objNull); // Pass the address of objNull
  v11->reset(); // required
  if ( height > 0 )
  {
    v12 = 0;
    char* v13 = outptr + (height - 1) * width_in_padded_4bytes;
    do
    {
      ++v12;
      for (int i = 0; i < width_in_padded_bytes; i++)
        {
          *(v13 + i) = 0xFF & (v11->getChar() ^ 0xFF);
        }
      v13 -= width_in_padded_4bytes;
    }
    while ( v12 != height );
  }
  return 0;
}

**Comment by HinTak** [comment]
The poppler code seems to have changed. Anyway, here is the alternative to build with jbig2dec : just `git clone --recursive https://github.com/caj2pdf/caj2pdf-extra-libs` then run `./build.sh` . (I wrote it yesterday to build for mac os x, but it is identical).

**Comment by HinTak** [comment]
The poppler code hasn't changed - it still works against current poppler on Linux (23.08.0 I have on my system). @tpofo what version do you have, and on what system did you see that error message?

It seems that you have a really old libpoppler (more than 3 years old) on your system?
