### ISSUE TITLE
需要协助？

### ISSUE THREAD

**Issue by yangxianheng** [caj2pdf/caj2pdf#80]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/caj2pdf/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 CAJ2PDF？

github

2) 你的使用场景是什么？比如convert还是其他。

convert

3) 你看到的不正常的现象是什么？（请描述具体现象，比如PDF打不开等）

Nice work。如果有需要我可以为代码添加一些注释，并整理为PyPI可以上传的格式。我看到有另一个包 `restructured` 。
不过里面的不是Github最新版本。
不过即使是最新版本也无法解决我的问题。

现在我面临的问题是我想修改其中的问题，不过看不懂代码。
如果有需要的话我可以撰写一些注释并尝试理解代码。

在下不才，8年python经验，稍微上架了几个pypi开源库。
有能力做这个事情。
（此为小号）

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（Python版本、Python包版本以及mutools版本）。

7) 请使用××ZIP××格式压缩CAJ文件，附在此处。

8)  请附上出错时软件输出的错误信息。

错误信息:

```python
    # 软件输出的错误信息
```

请预览一下你填的内容再提交。

**Comment by HinTak** [comment]
@yangxianheng 你如果有不能轉化的文本，請用attach 功能附上。
