### ISSUE TITLE
Releases中没有文件？

### ISSUE THREAD

**Issue by Knowledge-action** [caj2pdf/caj2pdf#81]
您好，我不懂编程，您的程序没有在Releases中，我就不知道如何获取您的这个软件了，我是Win10系统，您这个有exe文件吗？

**Comment by IEXPECTATION** [comment]
这个是命令行工具，在download哪里下载zip包解压，再解压后的目录下使用cmd后者windows terminal，然后就可以使用了。当然最推荐使用git克隆（git clone https://github.com/caj2pdf/caj2pdf.git）。

**Comment by tomsux** [comment]
> 这个是命令行工具，在code那里下载zip包解压，在解压后的目录下使用cmd或者windows terminal，然后就可以使用了。当然最推荐使用git克隆（git clone [https://github.com/caj2pdf/caj2pdf.git）。](https://github.com/caj2pdf/caj2pdf.git%EF%BC%89%E3%80%82)

ubuntu下要怎么用呢,也是这样吗

**Comment by HinTak** [comment]
See "how to use " section in https://github.com/caj2pdf/caj2pdf#readme
