### ISSUE TITLE
Rewrite in Go

### ISSUE THREAD

**Issue by rwv** [caj2pdf/caj2pdf#84]
用 golang 重写了部分，现在写完了 CAJ 。

主要目标是静态编译成一个可执行文件。

https://github.com/rwv/caj2pdf-go

**Comment by ailinwang** [comment]
> 用 golang 重写了部分，现在写完了 CAJ 。
> 
> 主要目标是静态编译成一个可执行文件。
> 
> https://github.com/rwv/caj2pdf-go

这个仓库很久没更新了，关了这个issue吧

**Comment by HinTak** [comment]
I have put the info under https://github.com/caj2pdf/caj2pdf/wiki .
