### ISSUE TITLE
纯文字的hn格式后续会支持吗？？？

### ISSUE THREAD

**Issue by kwinzhang** [caj2pdf/caj2pdf#96]
纯文字的hn格式后续会支持吗？？？哪位大佬有时间研究下？？

**Comment by HinTak** [comment]
If you have a sample, it would be useful to post, otherwise it is somewhat wasting everybody's time to start a new issue, when you could just ask in one of the existing issues about text-only hn files. There are already quite a few.

I guess the answer is, please feel free to work on it yourself. Wasting people's time also have the effect of decreasing the chance of this issue being worked on, since answering such questions waste the same time that might have worked on that issue.

**Comment by lelandyang** [comment]
> 纯文字的hn格式后续会支持吗？？？哪位大佬有时间研究下？？

Sadly, as far as I can see, there's no recent plan for implementing it.
Technically speaking, it is not too hard to implement, and yet there are two issues unlikely to address.
(1) Pure-text HN files includes intellectual property problem that is hard to bypass, legal issue is a huge concern;
(2) It is not too hard and yet it will be a time-consuming task to implement a parser that is compatible with all pure-text hn files. which is not worthwhile as pure-text NH files are merely used in old CAJ files, mostly before 2007, and they are only used as a format in magazines,, which can also be downloaded in PDF format directly from the website. 
While Hintak's reply is rude and ruthless, he means no harm.

**Comment by HinTak** [comment]
There are 3 or 4 currently open issues about this already, I see no reason of starting a new thread, with no additional input. As I wrote, asking about it, and wasting people's time responding (or reading responses - that applies to you too, @lelandyang) , is wasting time that could have been spent on actually doing it.

Next time, it is best just to close such an issue quickly as a duplicate of one of the others, without comment/response.

**Comment by lelandyang** [comment]
> There are 3 or 4 currently open issues about this already, I see no reason of starting a new thread, with no additional input. As I wrote, asking about it, and wasting people's time responding (or reading responses - that applies to you too, @lelandyang) , is wasting time that could have been spent on actually doing it.
> 
> Next time, it is best just to close such an issue quickly as a duplicate of one of the others, without comment/response.

The reply was not intended for you, you are wasting your own time refraining.
An explanation is always better than a "waste of time" scolding. Demanding users always exist, you can always close an issue without bxxxxing around.

**Comment by HinTak** [comment]
There is only a limited time spent on open-source projects for everybody. Out of that, a small fraction, x is for caj2pdf. If amount of time, y, is spent on closing off issues like this, then (x - y) is left for any coding at all.

And if y is bigger than x, then, there is no time left for any coding, and nothing will get done.

Try making a +ve contribution, like posting a sample. Asking questions repeatedly, particularly of the forms of: "is anybody working on this", "when is it getting done", "why is nobody working on this", "why is people not reading my postings" are called negative contributions.
